[global]
  server role = standalone server
  server string = Home Creative Storage
  workgroup = WORKGROUP
  security = user
  map to guest = Never
  restrict anonymous = 2
  server min protocol = SMB3_00
  server smb encrypt = required
  smb ports = 445
  disable netbios = yes
  load printers = no
  printing = bsd
  printcap name = /dev/null
  log level = 1
  logging = stdout
  fruit:aapl = yes

[Creative]
  path = /shares/Creative
  valid users = egouda
  read only = no
  guest ok = no
  browseable = yes
  force user = egouda
  force group = creative
  create mask = 0660
  directory mask = 0770
  vfs objects = fruit streams_xattr
  fruit:metadata = stream
  fruit:resource = file
  fruit:posix_rename = yes
  ea support = yes
  store dos attributes = yes
  follow symlinks = no
  wide links = no
